name: Lint, Test, Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
        run: npm lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: npm build
